name: Build and Push Docker image to Docker Hub

on:
  push:
    branches: ["master", "main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # if you have code in your own folder you can mention here
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/testrepo:latest

  # this is deploy the code on ec2 instance right now I do't have active instances will keep of todo mode

  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Pull image from docker hub
  #       run: docker pull prashantmalakoti701/testrepo:latest
  #     - name: Delete old container
  #       run: docker rm -f testrepo-container
  #     - name: Run Docker Container
  #       run: docker run -d -p 3000:3000 --name testrepo-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' prashantmalakoti701/testrepo
